### ISSUE TITLE
add a reset button 

### ISSUE THREAD

**Issue by mjmajadly** [WebAhead7/fishy#4]
I think it would be good to have a reset button on top of the tank where a user can reset the game if they want. 
Or have a home page where the user can click 'start game', and in the game they can click 'home' to exist the game (easier that a reset button maybe)

when you add multiple fish it takes long time to wait for each one to die. This way the user can go back and restart the game if they want

**Comment by halaassaly** [comment]
nice idea !!
Added a "Restart" button as you suggested.
fixed :)
